install: brew
description: Syntax-highlighting pager for git and diff
post_install:
  - git config --global core.pager delta
  - git config --global interactive.diffFilter 'delta --color-only'
  - git config --global delta.navigate true
  - git config --global merge.conflictStyle zdiff3
